desc "Pick a random user as the winner"
task :load_subjects => :environment do
  subjects = [['Math', 'Basic Math'],
  ['Math', 'Arithmetic'],
  ['Math', 'PreAlgebra'],
  ['Math', 'Algebra'],
  ['Math', 'Geometry'],
  ['Math', 'PreCalculus'],
  ['Math', 'Calculus'],
  ['Math', 'Trigonometry'],
  ['Math', 'Theory'],
  ['Math', 'Applied Math'],
  ['Math', 'Statistics'],
  ['Math', 'Fractals'],
  ['Science', 'Biology'],
  ['Science', 'Chemistry'],
  ['Science', 'Earth Science'],
  ['Science', 'Astronomy'],
  ['Science', 'Engineering'],
  ['Science', 'Physics'],
  ['Science', 'Psychology'],
  ['Science', 'Sociology'],
  ['Humanities', 'Philosophy'],
  ['Humanities', 'Religion'],
  ['Humanities', 'Linquistics'],
  ['Humanities', 'World Cultures'],
  ['Art', 'Digital'],
  ['Art', 'Visual Design'],
  ['Art', 'Painting'],
  ['Art', 'Photography'],
  ['Art', 'Theatre'],
  ['Art', 'Music'],
  ['Art', 'Art History'],
  ['Language', 'Italian'],
  ['Language', 'Japanese'],
  ['Language', 'French'],
  ['Language', 'English'],
  ['Language', 'Russian'],
  ['Language', 'Spanish'],
  ['Language', 'Hindi'],
  ['Language', 'Mandarin'],
  ['Language', 'Javamese'],
  ['Language', 'Arabic'],
  ['Language', 'Portuguese'],
  ['Language', 'Bengali'],
  ['Language', 'German'],
  ['Language', 'Hebrew'],
  ['Language', 'Irish'],
  ['Language', 'Polish'],
  ['Language', 'Swedish'],
  ['Language', 'Turkish'],
  ['Language', 'Korean'],
  ['Language', 'Vietnamese'],
  ['Language', 'Klingon'],
  ['Literature', 'Poetry'],
  ['Literature', 'Grammar'],
  ['Literature', 'Reading'],
  ['Literature', 'Creative Writing'],
  ['Literature', 'Fiction'],
  ['Literature', 'Non Fiction'],
  ['History', 'World History'],
  ['History', 'African American History'],
  ['History', 'Western Civilization'],
  ['History', 'Latin American History'],
  ['History', 'European History'],
  ['History', 'American History'],
  ['History', 'Far Eastern History'],
  ['History', 'World Religion']]
  subjects.each do |topic, sub_topic|
    Subject.create(topic: topic, sub_topic: sub_topic)
  end
end
